export const bookshelf = [
  {
    id: "skin-in-the-game",
    title: "Skin in the Game",
    author: "Nassim Nicholas Taleb",
    subject: "Risk & symmetry",
    color: "#8a4435",
    href: "/reading-collection/skin-in-the-game-summary.html",
  },
  {
    id: "good-to-great",
    title: "Good to Great",
    author: "Jim Collins",
    subject: "Leadership",
    color: "#315d54",
    href: "/reading-collection/good-to-great-summary.html",
  },
  {
    id: "no-rules-rules",
    title: "No Rules Rules",
    author: "Reed Hastings & Erin Meyer",
    subject: "Culture",
    color: "#6c3850",
    href: "/reading-collection/no-rules-rules-summary.html",
  },
  {
    id: "the-lean-startup",
    title: "The Lean Startup",
    author: "Eric Ries",
    subject: "Product & innovation",
    color: "#32556a",
    href: "/reading-collection/the-lean-startup-summary.html",
  },
  {
    id: "the-hard-thing-about-hard-things",
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    subject: "Building & deciding",
    color: "#745a32",
    href: "/reading-collection/the-hard-thing-about-hard-things-summary.html",
  },
  {
    id: "influence",
    title: "Influence",
    author: "Robert B. Cialdini",
    subject: "Psychology",
    color: "#524969",
    href: "/reading-collection/influence-book-summary.html",
  },
] as const;
